# Generated by Django 2.0.5 on 2018-05-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('a', 'available'), ('p', 'pending'), ('r', 'rejected')], max_length=10)),
            ],
        ),
    ]
