# Generated by Django 2.0.5 on 2018-05-31 10:32

import candidate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[(candidate.models.Candidate.Status('available'), 'available'), (candidate.models.Candidate.Status('pending'), 'pending'), (candidate.models.Candidate.Status('rejected'), 'rejected')], max_length=10),
        ),
    ]
